{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "exec-email-copilot.fullname" . }}
  labels:
    {{- include "exec-email-copilot.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secret }}
  {{- range $key, $val := . }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
{{- end }}
